package com.sto.szdataobject.model.pojo;

public class priceDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.id
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.name
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.price
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    private String price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.id
     *
     * @return the value of price.id
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.id
     *
     * @param id the value for price.id
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.name
     *
     * @return the value of price.name
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.name
     *
     * @param name the value for price.name
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.price
     *
     * @return the value of price.price
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.price
     *
     * @param price the value for price.price
     *
     * @mbg.generated Wed May 20 11:03:42 CST 2020
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }
}