package com.sto.szdataobject.model.pojo;

public class szCollectDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.id
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.brand
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.productName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.duty
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.nameModel
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String namemodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.number
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.weight
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.priceAddress
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String priceaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.englishProductName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String englishproductname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.allProductName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String allproductname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.fromCountry
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String fromcountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.unit
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szcollect.bizhi
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    private String bizhi;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.id
     *
     * @return the value of szcollect.id
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.id
     *
     * @param id the value for szcollect.id
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.brand
     *
     * @return the value of szcollect.brand
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.brand
     *
     * @param brand the value for szcollect.brand
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.productName
     *
     * @return the value of szcollect.productName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.productName
     *
     * @param productname the value for szcollect.productName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.duty
     *
     * @return the value of szcollect.duty
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.duty
     *
     * @param duty the value for szcollect.duty
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.nameModel
     *
     * @return the value of szcollect.nameModel
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getNamemodel() {
        return namemodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.nameModel
     *
     * @param namemodel the value for szcollect.nameModel
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setNamemodel(String namemodel) {
        this.namemodel = namemodel == null ? null : namemodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.number
     *
     * @return the value of szcollect.number
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.number
     *
     * @param number the value for szcollect.number
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.weight
     *
     * @return the value of szcollect.weight
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.weight
     *
     * @param weight the value for szcollect.weight
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.priceAddress
     *
     * @return the value of szcollect.priceAddress
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getPriceaddress() {
        return priceaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.priceAddress
     *
     * @param priceaddress the value for szcollect.priceAddress
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setPriceaddress(String priceaddress) {
        this.priceaddress = priceaddress == null ? null : priceaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.englishProductName
     *
     * @return the value of szcollect.englishProductName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getEnglishproductname() {
        return englishproductname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.englishProductName
     *
     * @param englishproductname the value for szcollect.englishProductName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setEnglishproductname(String englishproductname) {
        this.englishproductname = englishproductname == null ? null : englishproductname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.allProductName
     *
     * @return the value of szcollect.allProductName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getAllproductname() {
        return allproductname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.allProductName
     *
     * @param allproductname the value for szcollect.allProductName
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setAllproductname(String allproductname) {
        this.allproductname = allproductname == null ? null : allproductname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.fromCountry
     *
     * @return the value of szcollect.fromCountry
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getFromcountry() {
        return fromcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.fromCountry
     *
     * @param fromcountry the value for szcollect.fromCountry
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setFromcountry(String fromcountry) {
        this.fromcountry = fromcountry == null ? null : fromcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.unit
     *
     * @return the value of szcollect.unit
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.unit
     *
     * @param unit the value for szcollect.unit
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szcollect.bizhi
     *
     * @return the value of szcollect.bizhi
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public String getBizhi() {
        return bizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szcollect.bizhi
     *
     * @param bizhi the value for szcollect.bizhi
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    public void setBizhi(String bizhi) {
        this.bizhi = bizhi == null ? null : bizhi.trim();
    }
}