package com.sto.szdataobject.dao;

import com.sto.szdataobject.model.pojo.szCollectDao;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.List;

@Repository
public interface szCollectDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szcollect
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    int insert(szCollectDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szcollect
     *
     * @mbg.generated Tue Aug 11 23:24:58 CST 2020
     */
    int insertSelective(szCollectDao record);

    List<szCollectDao> selectInfoByBrand(@Param("brand") String brand, @Param("productName") String productName, @Param("number") String number, @Param("nameModel")String nameModel,@Param("weight")String weight);

    List<szCollectDao> selectInfoByProductName(@Param("brand") String productName);

    List<szCollectDao> selectInfoByOrBrand(@Param("brand") String brand, @Param("productName") String productName, @Param("number") String number, @Param("nameModel")String nameModel,@Param("weight")String weight);

    List<szCollectDao> selectInfoByIk(HashMap map);
}